source "https://rubygems.org"

ruby ">= 3.1"

gem "actionpack", "~> 7.1.3", ">= 7.1.3.4"
gem "actionview", "~> 7.1.3", ">= 7.1.3.4"
gem "railties", "~> 7.1.3", ">= 7.1.3.4"
gem "coupling", path: "../.."

group :development do
  gem "puma", "~> 6.0"
end

group :test do
  gem "minitest", "~> 5.16"
end
